work_dir: ./work_dir/kinetics/joint
model_saved_name: ./runs/ki_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ./data/kinetics_min_skeleton/train_data_joint.npy
  label_path: ./data/kinetics_min_skeleton/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ./data/kinetics_min_skeleton/val_data_joint.npy
  label_path: ./data/kinetics_min_skeleton/val_label.pkl

# model
model: model.graph2net.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 60]
warm_up_epoch: 5

# training
device: [0, 1]
batch_size: 64
test_batch_size: 64
num_epoch: 70
nesterov: True