work_dir: ./work_dir/ntu120/xset/bone
model_saved_name: ./runs/ntu120_ce_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xset/train_data_bone.npy
  label_path: ./data/ntu120/xset/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xset/val_data_bone.npy
  label_path: ./data/ntu120/xset/val_label.pkl

# model
model: model.graph2net.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 60]
warm_up_epoch: 5

# training
device: [0, 1]
batch_size: 32
test_batch_size: 32
num_epoch: 70
nesterov: True